#开发环境配置
server:
  #端口
  port: 8080
  tomcat:
    uri-encoding: utf-8

mybatis:
  # 配置xml 的扫描路径
  mapper-locations: classpath*:mybatis/mapper/*.xml
  check-config-location: true
  type-aliases-package: com.lingc.oilcard.domain
#logging:
#  config: logback.xml.bak

#数据库设置
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      name: druid
      initialSize: 15
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
  #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      druid:
        min-idle: 1000
        max-active: 6000
        max-wait: 6000
      url: jdbc:mysql://localhost:3306/oilcard?characterEncoding=utf-8
